{% set name = "crystal-toolkit" %}
{% set version = "2024.10.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crystal_toolkit-{{ version }}.tar.gz
  sha256: 6914ef15f6e105a51dc2f892670feeb0e92c86d3b4ad88357c27c3cfd3b20cf8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2,<8
    - jupyter_packaging
    - pip
  run:
    - python >={{ python_min }}
    - crystaltoolkit-extension
    - dash-mp-components >=0.4.38
    - dash >=2.11.0
    - flask-caching
    - frozendict
    - pymatgen
    - scikit-image
    - scikit-learn
    - shapely
    - webcolors
    - pydantic-settings
    - mp-api
    - jupyterlab >=3

test:
  imports:
    - crystal_toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/crystaltoolkit
  summary: Crystal Toolkit is a web app framework from the Materials Project
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab-extension/LICENSE

extra:
  recipe-maintainers:
    - awvwgk
